### ISSUE TITLE
Max () arg is an empty sequence

### ISSUE THREAD

**Issue by sdowning27** [marcrusso/DROPA#1]
The sample code and Test hg19 data worked perfectly. 

I attempted to edit the code to run the NT2 data with mouse mm9

I used this code - 
python3 DROPA_v1.0.0.py -ref GeneReference/mm9_RefSeq/ -o NT2_TEST -ex /Users/sdowning/DROPA/DROPA/Test_Datasets/NT2_DRIPc_UCSC_expression.TPM -shuffle 2 -gsize GeneReference/mm9.genome /Users/sdowning/DROPA/DROPA/Test_Datasets/NT2_DRIPc_peaks.bed

But it keeps outputting the same error:
**Traceback (most recent call last):
  File "DROPA_v1.0.0.py", line 51, in <module>
    checkresults = core.CheckExpression(gainresults[0],rnaSeq,limit=limit,peakname=data2,TSSTTSdistance=distance)
  File "/Users/sdowning/DROPA/DROPA/DROPAcore.py", line 160, in CheckExpression
    maxfpkm = max(fpkm)
ValueError: max() arg is an empty sequence**

I have some mouse data that I would also like to use and when I attempted to use it, I received the same ValueError
"max() arg is an empty sequence"

I thought this might be due to the reference or how the FPKM/TPM are annotated? 
I'm not sure if this is an issue but also couldn't figure out how to resolve.

**Comment by marcrusso** [comment]
This is due to the reference. NT2 cells are mapped on hg19 genome, you cant use mm9 reference.
If you have mouse gene expression data, i suggest you to donwnload the gene reference .gtf from UCSC Table Browser (in this case mm9 RefSeq) and use it for quantification.

**Comment by sdowning27** [comment]
Thank You! Sorry for the confusion.

**Comment by marcrusso** [comment]
Than you for using DROPA! Let me know if you have any other issue!
